name: qcarchive-docs
channels:
    - conda-forge
dependencies:
    - python=3
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - pandoc
    - pygments
    - nbformat
    - jupyter_client

      # Depends
    - qcportal

    - pip:
      - git+git://github.com/MolSSI/qcarchive-sphinx-theme#egg=qcarchive_sphinx_theme
